steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/vb2x-395719/vb2x', './docker/']
# Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/vb2x-395719/vb2x']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'server-aa69', '--image', 'gcr.io/vb2x-395719/vb2x', '--region', 'us-central1']
images:
- gcr.io/vb2x-395719/vb2x