# Generated by Django 4.2.4 on 2023-08-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_players', models.IntegerField(default=4, help_text='Enter the total number of players for this round.')),
                ('non_exclusions', models.CharField(blank=True, default='', help_text='Enter field documentation', max_length=20)),
            ],
            options={
                'ordering': ['-num_players', 'non_exclusions'],
            },
        ),
    ]
