# Generated by Django 4.2.4 on 2023-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play', '0003_alter_round_options_rename_pubdate_round_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='message',
            field=models.TextField(default=None, help_text='The court assignment results.', null=True),
        ),
    ]
