# Generated by Django 4.2.4 on 2023-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play', '0006_round_created_at_round_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-created_at', '-num_players', 'non_exclusions']},
        ),
        migrations.RemoveField(
            model_name='round',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='round',
            name='_message',
            field=models.TextField(blank=True, default=None, help_text='The court assignment results.', null=True),
        ),
    ]
