# Generated by Django 4.2.4 on 2023-08-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbcourtassign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_exclusions', models.CharField(max_length=200)),
                ('num_players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbcourtassign.vbroundmodel')),
            ],
        ),
    ]
